apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: minio-console-letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: rendyananta66@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: minio-console-tls-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
